version: "3"

services:
  candle:
    container_name: candle
    build:
      context: .
      dockerfile: devDockerfile
    environment:
      - GO_ENV=docker
      - POSTGRES_URI=${candle_POSTGRES_URI}
    volumes:
      - .:/go/src/github.com/dongri/candle
    logging:
      options:
        max-size: "500k"
    ports:
      - "127.0.0.1:3001:3001"
